# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 15:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BottomTuner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FP', 'FacePlate'), ('UBP', 'Upper BlockerPlate'), ('LBP', 'Lower BlockerPlate'), ('HTR', 'Pedestal Heater'), ('GB', 'GasBox'), ('TT', 'Top Tuner'), ('BT', 'Bottom Tuner'), ('OTH', 'Other')], max_length=3)),
                ('discription', models.CharField(max_length=300)),
                ('serial_number', models.CharField(max_length=50)),
                ('entry_time', models.DateTimeField(default=datetime.datetime(2016, 6, 26, 15, 15, 29, 125000, tzinfo=utc))),
                ('name', models.CharField(default='BKM BottomTuner', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DepChamber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('configure_start_time', models.DateTimeField(default=datetime.datetime(2016, 6, 26, 15, 15, 29, 222000, tzinfo=utc), verbose_name='Configuration starting time')),
                ('configure_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Configuration end time')),
                ('bt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.BottomTuner', verbose_name='the installed BottomTuner')),
            ],
        ),
        migrations.CreateModel(
            name='FacePlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FP', 'FacePlate'), ('UBP', 'Upper BlockerPlate'), ('LBP', 'Lower BlockerPlate'), ('HTR', 'Pedestal Heater'), ('GB', 'GasBox'), ('TT', 'Top Tuner'), ('BT', 'Bottom Tuner'), ('OTH', 'Other')], max_length=3)),
                ('discription', models.CharField(max_length=300)),
                ('serial_number', models.CharField(max_length=50)),
                ('entry_time', models.DateTimeField(default=datetime.datetime(2016, 6, 26, 15, 15, 29, 125000, tzinfo=utc))),
                ('name', models.CharField(default='BKM FacePlate', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GasBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FP', 'FacePlate'), ('UBP', 'Upper BlockerPlate'), ('LBP', 'Lower BlockerPlate'), ('HTR', 'Pedestal Heater'), ('GB', 'GasBox'), ('TT', 'Top Tuner'), ('BT', 'Bottom Tuner'), ('OTH', 'Other')], max_length=3)),
                ('discription', models.CharField(max_length=300)),
                ('serial_number', models.CharField(max_length=50)),
                ('entry_time', models.DateTimeField(default=datetime.datetime(2016, 6, 26, 15, 15, 29, 125000, tzinfo=utc))),
                ('name', models.CharField(default='BKM GasBox', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LowerBlockerPlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FP', 'FacePlate'), ('UBP', 'Upper BlockerPlate'), ('LBP', 'Lower BlockerPlate'), ('HTR', 'Pedestal Heater'), ('GB', 'GasBox'), ('TT', 'Top Tuner'), ('BT', 'Bottom Tuner'), ('OTH', 'Other')], max_length=3)),
                ('discription', models.CharField(max_length=300)),
                ('serial_number', models.CharField(max_length=50)),
                ('entry_time', models.DateTimeField(default=datetime.datetime(2016, 6, 26, 15, 15, 29, 125000, tzinfo=utc))),
                ('name', models.CharField(default='BKM LowerBlockerPlate', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FP', 'FacePlate'), ('UBP', 'Upper BlockerPlate'), ('LBP', 'Lower BlockerPlate'), ('HTR', 'Pedestal Heater'), ('GB', 'GasBox'), ('TT', 'Top Tuner'), ('BT', 'Bottom Tuner'), ('OTH', 'Other')], max_length=3)),
                ('discription', models.CharField(max_length=300)),
                ('serial_number', models.CharField(max_length=50)),
                ('entry_time', models.DateTimeField(default=datetime.datetime(2016, 6, 26, 15, 15, 29, 125000, tzinfo=utc))),
                ('name', models.CharField(default='BKM OtherParts', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PedestalHeater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FP', 'FacePlate'), ('UBP', 'Upper BlockerPlate'), ('LBP', 'Lower BlockerPlate'), ('HTR', 'Pedestal Heater'), ('GB', 'GasBox'), ('TT', 'Top Tuner'), ('BT', 'Bottom Tuner'), ('OTH', 'Other')], max_length=3)),
                ('discription', models.CharField(max_length=300)),
                ('serial_number', models.CharField(max_length=50)),
                ('entry_time', models.DateTimeField(default=datetime.datetime(2016, 6, 26, 15, 15, 29, 125000, tzinfo=utc))),
                ('name', models.CharField(default='BKM PedestalHeater', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopTuner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FP', 'FacePlate'), ('UBP', 'Upper BlockerPlate'), ('LBP', 'Lower BlockerPlate'), ('HTR', 'Pedestal Heater'), ('GB', 'GasBox'), ('TT', 'Top Tuner'), ('BT', 'Bottom Tuner'), ('OTH', 'Other')], max_length=3)),
                ('discription', models.CharField(max_length=300)),
                ('serial_number', models.CharField(max_length=50)),
                ('entry_time', models.DateTimeField(default=datetime.datetime(2016, 6, 26, 15, 15, 29, 125000, tzinfo=utc))),
                ('name', models.CharField(default='BKM TopTuner', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UpperBlockerPlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FP', 'FacePlate'), ('UBP', 'Upper BlockerPlate'), ('LBP', 'Lower BlockerPlate'), ('HTR', 'Pedestal Heater'), ('GB', 'GasBox'), ('TT', 'Top Tuner'), ('BT', 'Bottom Tuner'), ('OTH', 'Other')], max_length=3)),
                ('discription', models.CharField(max_length=300)),
                ('serial_number', models.CharField(max_length=50)),
                ('entry_time', models.DateTimeField(default=datetime.datetime(2016, 6, 26, 15, 15, 29, 125000, tzinfo=utc))),
                ('name', models.CharField(default='BKM UpperBlockerPlate', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='depchamber',
            name='fp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.FacePlate', verbose_name='the installed FacePlate'),
        ),
        migrations.AddField(
            model_name='depchamber',
            name='gb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.GasBox', verbose_name='the installed GasBox'),
        ),
        migrations.AddField(
            model_name='depchamber',
            name='htr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.PedestalHeater', verbose_name='the installed PedestalHeater'),
        ),
        migrations.AddField(
            model_name='depchamber',
            name='lbp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.LowerBlockerPlate', verbose_name='the installed Lower BlockerPlate'),
        ),
        migrations.AddField(
            model_name='depchamber',
            name='oth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.OtherParts', verbose_name='the installed other parts'),
        ),
        migrations.AddField(
            model_name='depchamber',
            name='tt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.TopTuner', verbose_name='the installed TopTuner'),
        ),
        migrations.AddField(
            model_name='depchamber',
            name='ubp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.UpperBlockerPlate', verbose_name='the installed Upper BlockerPlate'),
        ),
    ]
