# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foup_slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foup', models.CharField(max_length=100)),
                ('slot', models.CharField(choices=[('1', 'Slot 1'), ('2', 'Slot 2'), ('3', 'Slot 3'), ('4', 'Slot 4'), ('5', 'Slot 5'), ('6', 'Slot 6'), ('7', 'Slot 7'), ('8', 'Slot 8'), ('9', 'Slot 9'), ('10', 'Slot 10'), ('11', 'Slot 11'), ('12', 'Slot 12'), ('13', 'Slot 13'), ('14', 'Slot 14'), ('15', 'Slot 15'), ('16', 'Slot 16'), ('17', 'Slot 17'), ('18', 'Slot 18'), ('19', 'Slot 19'), ('20', 'Slot 20'), ('21', 'Slot 21'), ('22', 'Slot 22'), ('23', 'Slot 23'), ('24', 'Slot 24'), ('25', 'Slot 25')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Wafer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wafer_type', models.CharField(choices=[('RCL', 'Reclaimed Wafer'), ('MEC', 'Mechanical Grade Wafer'), ('PTC', 'Particle Grade Wafer'), ('LRP', 'Low-Resistivity Particle Grade Wafer')], max_length=3)),
                ('is_used', models.BooleanField(default=False)),
                ('foup_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foup.Foup_slot')),
            ],
        ),
    ]
