# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 04:39
from __future__ import unicode_literals

from django.db import migrations
import foup.models.slot_class


class Migration(migrations.Migration):

    dependencies = [
        ('foup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foup_slot',
            name='slot',
            field=foup.models.slot_class.IntegerRangeField(),
        ),
    ]
