# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 01:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('runsheet1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottomtuner',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 12, 1, 14, 10, 513000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='depchamber',
            name='bt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runsheet1.BottomTuner', verbose_name='the installed BottomTuner'),
        ),
        migrations.AlterField(
            model_name='depchamber',
            name='configure_start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 12, 1, 14, 10, 518000, tzinfo=utc), verbose_name='Configuration starting time'),
        ),
        migrations.AlterField(
            model_name='depchamber',
            name='fp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runsheet1.FacePlate', verbose_name='the installed FacePlate'),
        ),
        migrations.AlterField(
            model_name='depchamber',
            name='gb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runsheet1.GasBox', verbose_name='the installed GasBox'),
        ),
        migrations.AlterField(
            model_name='depchamber',
            name='htr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runsheet1.PedestalHeater', verbose_name='the installed PedestalHeater'),
        ),
        migrations.AlterField(
            model_name='depchamber',
            name='lbp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runsheet1.LowerBlockerPlate', verbose_name='the installed Lower BlockerPlate'),
        ),
        migrations.AlterField(
            model_name='depchamber',
            name='tt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runsheet1.TopTuner', verbose_name='the installed TopTuner'),
        ),
        migrations.AlterField(
            model_name='depchamber',
            name='ubp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runsheet1.UpperBlockerPlate', verbose_name='the installed Upper BlockerPlate'),
        ),
        migrations.AlterField(
            model_name='faceplate',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 12, 1, 14, 10, 513000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='gasbox',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 12, 1, 14, 10, 513000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lowerblockerplate',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 12, 1, 14, 10, 513000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='otherparts',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 12, 1, 14, 10, 513000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pedestalheater',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 12, 1, 14, 10, 513000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='toptuner',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 12, 1, 14, 10, 513000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='upperblockerplate',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 12, 1, 14, 10, 513000, tzinfo=utc)),
        ),
    ]
