# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 01:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('runsheet1', '0002_auto_20160611_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottomtuner',
            name='category',
            field=models.CharField(choices=[('FP', 'FacePlate'), ('UBP', 'Upper BlockerPlate'), ('LBP', 'Lower BlockerPlate'), ('HTR', 'Pedestal Heater'), ('GB', 'GasBox'), ('TT', 'Top Tuner'), ('BT', 'Bottom Tuner'), ('OTH', 'Other')], default='BT', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faceplate',
            name='category',
            field=models.CharField(choices=[('FP', 'FacePlate'), ('UBP', 'Upper BlockerPlate'), ('LBP', 'Lower BlockerPlate'), ('HTR', 'Pedestal Heater'), ('GB', 'GasBox'), ('TT', 'Top Tuner'), ('BT', 'Bottom Tuner'), ('OTH', 'Other')], default='FP', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gasbox',
            name='category',
            field=models.CharField(choices=[('FP', 'FacePlate'), ('UBP', 'Upper BlockerPlate'), ('LBP', 'Lower BlockerPlate'), ('HTR', 'Pedestal Heater'), ('GB', 'GasBox'), ('TT', 'Top Tuner'), ('BT', 'Bottom Tuner'), ('OTH', 'Other')], default='GB', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lowerblockerplate',
            name='category',
            field=models.CharField(choices=[('FP', 'FacePlate'), ('UBP', 'Upper BlockerPlate'), ('LBP', 'Lower BlockerPlate'), ('HTR', 'Pedestal Heater'), ('GB', 'GasBox'), ('TT', 'Top Tuner'), ('BT', 'Bottom Tuner'), ('OTH', 'Other')], default='LBP', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherparts',
            name='category',
            field=models.CharField(choices=[('FP', 'FacePlate'), ('UBP', 'Upper BlockerPlate'), ('LBP', 'Lower BlockerPlate'), ('HTR', 'Pedestal Heater'), ('GB', 'GasBox'), ('TT', 'Top Tuner'), ('BT', 'Bottom Tuner'), ('OTH', 'Other')], default='OTH', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedestalheater',
            name='category',
            field=models.CharField(choices=[('FP', 'FacePlate'), ('UBP', 'Upper BlockerPlate'), ('LBP', 'Lower BlockerPlate'), ('HTR', 'Pedestal Heater'), ('GB', 'GasBox'), ('TT', 'Top Tuner'), ('BT', 'Bottom Tuner'), ('OTH', 'Other')], default='HTR', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toptuner',
            name='category',
            field=models.CharField(choices=[('FP', 'FacePlate'), ('UBP', 'Upper BlockerPlate'), ('LBP', 'Lower BlockerPlate'), ('HTR', 'Pedestal Heater'), ('GB', 'GasBox'), ('TT', 'Top Tuner'), ('BT', 'Bottom Tuner'), ('OTH', 'Other')], default='TT', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upperblockerplate',
            name='category',
            field=models.CharField(choices=[('FP', 'FacePlate'), ('UBP', 'Upper BlockerPlate'), ('LBP', 'Lower BlockerPlate'), ('HTR', 'Pedestal Heater'), ('GB', 'GasBox'), ('TT', 'Top Tuner'), ('BT', 'Bottom Tuner'), ('OTH', 'Other')], default='UBP', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bottomtuner',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 12, 1, 31, 31, 50000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bottomtuner',
            name='name',
            field=models.CharField(default='BKM BottomTuner', max_length=20),
        ),
        migrations.AlterField(
            model_name='depchamber',
            name='configure_start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 12, 1, 31, 31, 57000, tzinfo=utc), verbose_name='Configuration starting time'),
        ),
        migrations.AlterField(
            model_name='faceplate',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 12, 1, 31, 31, 50000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faceplate',
            name='name',
            field=models.CharField(default='BKM FacePlate', max_length=20),
        ),
        migrations.AlterField(
            model_name='gasbox',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 12, 1, 31, 31, 50000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='gasbox',
            name='name',
            field=models.CharField(default='BKM GasBox', max_length=20),
        ),
        migrations.AlterField(
            model_name='lowerblockerplate',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 12, 1, 31, 31, 50000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lowerblockerplate',
            name='name',
            field=models.CharField(default='BKM LowerBlockerPlate', max_length=20),
        ),
        migrations.AlterField(
            model_name='otherparts',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 12, 1, 31, 31, 50000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='otherparts',
            name='name',
            field=models.CharField(default='BKM OtherParts', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedestalheater',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 12, 1, 31, 31, 50000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pedestalheater',
            name='name',
            field=models.CharField(default='BKM PedestalHeater', max_length=20),
        ),
        migrations.AlterField(
            model_name='toptuner',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 12, 1, 31, 31, 50000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='toptuner',
            name='name',
            field=models.CharField(default='BKM TopTuner', max_length=20),
        ),
        migrations.AlterField(
            model_name='upperblockerplate',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 12, 1, 31, 31, 50000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='upperblockerplate',
            name='name',
            field=models.CharField(default='BKM UpperBlockerPlate', max_length=20),
        ),
    ]
